# Generated by Django 5.0.6 on 2024-05-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_date_alter_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=0),
        ),
    ]
