# Generated by Django 5.0.6 on 2024-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_event_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_participants',
            field=models.IntegerField(default=0),
        ),
    ]
