# Generated by Django 5.0.6 on 2024-06-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_event_number_of_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('eventID', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
